server:
  port: 8081

spring:
  application:
    name: card-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/card_db
  
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: card-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: "com.marketplace.trade.event.CompraRealizadaEvent:com.marketplace.card.event.CompraRealizadaEvent"
      auto-offset-reset: earliest

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
  endpoint:
    health:
      show-details: always

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [card-service,correlationId=%X{correlationId}] %logger{36} - %msg%n"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
